Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,16 +33,21 @@ jobs:
         with:
           python-version: '3.x'
 
-      - name: Install AWS CLI
-        run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
-
       - name: Install dependencies
         run: |
           pip install awscli
           pip install boto3
+
+      - name: Check if AWS CLI is already installed
+        run: |
+          if ! command -v aws &> /dev/null; then
+            echo "AWS CLI not found, installing it now."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          else
+            echo "AWS CLI already installed, skipping installation."
+          fi
 
       - name: Deploy Lambda Function
         run: |
